# Generated by Django 4.2 on 2023-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=' ', upload_to='', verbose_name='img/'),
            preserve_default=False,
        ),
    ]
