# Generated by Django 4.2 on 2023-07-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_created_at_remove_post_draft2'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
